URL=google.com
ParkName=Six Flags Magic Mountain
Email=develop@thetunagroup.com
Password=We67B@8us6er
Title=Largest Water & Amusement Parks in Darien Lake | Darien Lake | More characters.................................... | Six Flags Darien Lake
#LoginEmail=tunagold@yopmail.com
#LoginPassword=Qwerty12345@
LoginEmail=rahuldev1741@gmail.com
LoginPassword=Rahuldev1741@
SelectParkTitle=Six Flags | Six Flags
ParkHomeTitle=Six Flags Magic Mountain | Six Flags Magic Mountain
FirstName = rahul
LastName = rex
MobileNumber = (647) 384-5453
Dob = 11/01/1997
RetypePassword = Rahuldev1741@
forgot_URL = https://sixflags-web-dev.sfdev.co/account/forgot-password


